[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana = "FMrnRTKyLZPFK5BgZB7aGA95RVa3pVyvCtbR8oMov2n9"

[programs.devnet]
solana = "FMrnRTKyLZPFK5BgZB7aGA95RVa3pVyvCtbR8oMov2n9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/TMmF8KNbVDEHLZMXBU6Nz"
wallet = ".keys/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
